/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'

const AuthenticatedIndexLazyRouteImport = createFileRoute('/_authenticated/')()
const AuthenticatedUsersLazyRouteImport = createFileRoute(
  '/_authenticated/users',
)()
const AuthenticatedNotificationsLazyRouteImport = createFileRoute(
  '/_authenticated/notifications',
)()
const AuthenticatedBlankPageLazyRouteImport = createFileRoute(
  '/_authenticated/blank-page',
)()
const AuthenticatedUiComponentsTooltipLazyRouteImport = createFileRoute(
  '/_authenticated/ui-components/tooltip',
)()
const AuthenticatedUiComponentsToastLazyRouteImport = createFileRoute(
  '/_authenticated/ui-components/toast',
)()
const AuthenticatedUiComponentsTabsLazyRouteImport = createFileRoute(
  '/_authenticated/ui-components/tabs',
)()
const AuthenticatedUiComponentsSwitchLazyRouteImport = createFileRoute(
  '/_authenticated/ui-components/switch',
)()
const AuthenticatedUiComponentsSkeletonLazyRouteImport = createFileRoute(
  '/_authenticated/ui-components/skeleton',
)()
const AuthenticatedUiComponentsSheetLazyRouteImport = createFileRoute(
  '/_authenticated/ui-components/sheet',
)()
const AuthenticatedUiComponentsSeparatorLazyRouteImport = createFileRoute(
  '/_authenticated/ui-components/separator',
)()
const AuthenticatedUiComponentsSelectLazyRouteImport = createFileRoute(
  '/_authenticated/ui-components/select',
)()
const AuthenticatedUiComponentsScrollAreaLazyRouteImport = createFileRoute(
  '/_authenticated/ui-components/scroll-area',
)()
const AuthenticatedUiComponentsSchoolLazyRouteImport = createFileRoute(
  '/_authenticated/ui-components/school',
)()
const AuthenticatedUiComponentsRadioGroupLazyRouteImport = createFileRoute(
  '/_authenticated/ui-components/radio-group',
)()
const AuthenticatedUiComponentsProgressLazyRouteImport = createFileRoute(
  '/_authenticated/ui-components/progress',
)()
const AuthenticatedUiComponentsPopoverLazyRouteImport = createFileRoute(
  '/_authenticated/ui-components/popover',
)()
const AuthenticatedUiComponentsModalLazyRouteImport = createFileRoute(
  '/_authenticated/ui-components/modal',
)()
const AuthenticatedUiComponentsFormValidationLazyRouteImport = createFileRoute(
  '/_authenticated/ui-components/form-validation',
)()
const AuthenticatedUiComponentsFormLazyRouteImport = createFileRoute(
  '/_authenticated/ui-components/form',
)()
const AuthenticatedUiComponentsDropdownMenuLazyRouteImport = createFileRoute(
  '/_authenticated/ui-components/dropdown-menu',
)()
const AuthenticatedUiComponentsDatePickerLazyRouteImport = createFileRoute(
  '/_authenticated/ui-components/date-picker',
)()
const AuthenticatedUiComponentsDataTableLazyRouteImport = createFileRoute(
  '/_authenticated/ui-components/data-table',
)()
const AuthenticatedUiComponentsCompositeLazyRouteImport = createFileRoute(
  '/_authenticated/ui-components/composite',
)()
const AuthenticatedUiComponentsCollapsibleLazyRouteImport = createFileRoute(
  '/_authenticated/ui-components/collapsible',
)()
const AuthenticatedUiComponentsCheckboxLazyRouteImport = createFileRoute(
  '/_authenticated/ui-components/checkbox',
)()
const AuthenticatedUiComponentsCardLazyRouteImport = createFileRoute(
  '/_authenticated/ui-components/card',
)()
const AuthenticatedUiComponentsCalendarLazyRouteImport = createFileRoute(
  '/_authenticated/ui-components/calendar',
)()
const AuthenticatedUiComponentsButtonLazyRouteImport = createFileRoute(
  '/_authenticated/ui-components/button',
)()
const AuthenticatedUiComponentsBreadcrumbLazyRouteImport = createFileRoute(
  '/_authenticated/ui-components/breadcrumb',
)()
const AuthenticatedUiComponentsBadgeLazyRouteImport = createFileRoute(
  '/_authenticated/ui-components/badge',
)()
const AuthenticatedUiComponentsAvatarLazyRouteImport = createFileRoute(
  '/_authenticated/ui-components/avatar',
)()
const AuthenticatedUiComponentsAlertDialogLazyRouteImport = createFileRoute(
  '/_authenticated/ui-components/alert-dialog',
)()
const AuthenticatedUiComponentsAccordionLazyRouteImport = createFileRoute(
  '/_authenticated/ui-components/accordion',
)()
const AuthenticatedSettingsProfileLazyRouteImport = createFileRoute(
  '/_authenticated/settings/profile',
)()
const AuthenticatedSettingsAppearanceLazyRouteImport = createFileRoute(
  '/_authenticated/settings/appearance',
)()
const AuthenticatedErrors503LazyRouteImport = createFileRoute(
  '/_authenticated/errors/503',
)()
const AuthenticatedErrors500LazyRouteImport = createFileRoute(
  '/_authenticated/errors/500',
)()
const AuthenticatedErrors404LazyRouteImport = createFileRoute(
  '/_authenticated/errors/404',
)()
const AuthenticatedErrors403LazyRouteImport = createFileRoute(
  '/_authenticated/errors/403',
)()
const AuthenticatedErrors401LazyRouteImport = createFileRoute(
  '/_authenticated/errors/401',
)()

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexLazyRoute = AuthenticatedIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/index.lazy').then((d) => d.Route),
)
const AuthenticatedUsersLazyRoute = AuthenticatedUsersLazyRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/users.lazy').then((d) => d.Route),
)
const AuthenticatedNotificationsLazyRoute =
  AuthenticatedNotificationsLazyRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/notifications.lazy').then((d) => d.Route),
  )
const AuthenticatedBlankPageLazyRoute =
  AuthenticatedBlankPageLazyRouteImport.update({
    id: '/blank-page',
    path: '/blank-page',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/blank-page.lazy').then((d) => d.Route),
  )
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUiComponentsTooltipLazyRoute =
  AuthenticatedUiComponentsTooltipLazyRouteImport.update({
    id: '/ui-components/tooltip',
    path: '/ui-components/tooltip',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ui-components/tooltip.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUiComponentsToastLazyRoute =
  AuthenticatedUiComponentsToastLazyRouteImport.update({
    id: '/ui-components/toast',
    path: '/ui-components/toast',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ui-components/toast.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUiComponentsTabsLazyRoute =
  AuthenticatedUiComponentsTabsLazyRouteImport.update({
    id: '/ui-components/tabs',
    path: '/ui-components/tabs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ui-components/tabs.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUiComponentsSwitchLazyRoute =
  AuthenticatedUiComponentsSwitchLazyRouteImport.update({
    id: '/ui-components/switch',
    path: '/ui-components/switch',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ui-components/switch.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUiComponentsSkeletonLazyRoute =
  AuthenticatedUiComponentsSkeletonLazyRouteImport.update({
    id: '/ui-components/skeleton',
    path: '/ui-components/skeleton',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ui-components/skeleton.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUiComponentsSheetLazyRoute =
  AuthenticatedUiComponentsSheetLazyRouteImport.update({
    id: '/ui-components/sheet',
    path: '/ui-components/sheet',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ui-components/sheet.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUiComponentsSeparatorLazyRoute =
  AuthenticatedUiComponentsSeparatorLazyRouteImport.update({
    id: '/ui-components/separator',
    path: '/ui-components/separator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ui-components/separator.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUiComponentsSelectLazyRoute =
  AuthenticatedUiComponentsSelectLazyRouteImport.update({
    id: '/ui-components/select',
    path: '/ui-components/select',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ui-components/select.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUiComponentsScrollAreaLazyRoute =
  AuthenticatedUiComponentsScrollAreaLazyRouteImport.update({
    id: '/ui-components/scroll-area',
    path: '/ui-components/scroll-area',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ui-components/scroll-area.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUiComponentsSchoolLazyRoute =
  AuthenticatedUiComponentsSchoolLazyRouteImport.update({
    id: '/ui-components/school',
    path: '/ui-components/school',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ui-components/school.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUiComponentsRadioGroupLazyRoute =
  AuthenticatedUiComponentsRadioGroupLazyRouteImport.update({
    id: '/ui-components/radio-group',
    path: '/ui-components/radio-group',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ui-components/radio-group.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUiComponentsProgressLazyRoute =
  AuthenticatedUiComponentsProgressLazyRouteImport.update({
    id: '/ui-components/progress',
    path: '/ui-components/progress',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ui-components/progress.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUiComponentsPopoverLazyRoute =
  AuthenticatedUiComponentsPopoverLazyRouteImport.update({
    id: '/ui-components/popover',
    path: '/ui-components/popover',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ui-components/popover.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUiComponentsModalLazyRoute =
  AuthenticatedUiComponentsModalLazyRouteImport.update({
    id: '/ui-components/modal',
    path: '/ui-components/modal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ui-components/modal.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUiComponentsFormValidationLazyRoute =
  AuthenticatedUiComponentsFormValidationLazyRouteImport.update({
    id: '/ui-components/form-validation',
    path: '/ui-components/form-validation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ui-components/form-validation.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUiComponentsFormLazyRoute =
  AuthenticatedUiComponentsFormLazyRouteImport.update({
    id: '/ui-components/form',
    path: '/ui-components/form',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ui-components/form.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUiComponentsDropdownMenuLazyRoute =
  AuthenticatedUiComponentsDropdownMenuLazyRouteImport.update({
    id: '/ui-components/dropdown-menu',
    path: '/ui-components/dropdown-menu',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ui-components/dropdown-menu.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUiComponentsDatePickerLazyRoute =
  AuthenticatedUiComponentsDatePickerLazyRouteImport.update({
    id: '/ui-components/date-picker',
    path: '/ui-components/date-picker',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ui-components/date-picker.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUiComponentsDataTableLazyRoute =
  AuthenticatedUiComponentsDataTableLazyRouteImport.update({
    id: '/ui-components/data-table',
    path: '/ui-components/data-table',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ui-components/data-table.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUiComponentsCompositeLazyRoute =
  AuthenticatedUiComponentsCompositeLazyRouteImport.update({
    id: '/ui-components/composite',
    path: '/ui-components/composite',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ui-components/composite.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUiComponentsCollapsibleLazyRoute =
  AuthenticatedUiComponentsCollapsibleLazyRouteImport.update({
    id: '/ui-components/collapsible',
    path: '/ui-components/collapsible',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ui-components/collapsible.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUiComponentsCheckboxLazyRoute =
  AuthenticatedUiComponentsCheckboxLazyRouteImport.update({
    id: '/ui-components/checkbox',
    path: '/ui-components/checkbox',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ui-components/checkbox.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUiComponentsCardLazyRoute =
  AuthenticatedUiComponentsCardLazyRouteImport.update({
    id: '/ui-components/card',
    path: '/ui-components/card',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ui-components/card.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUiComponentsCalendarLazyRoute =
  AuthenticatedUiComponentsCalendarLazyRouteImport.update({
    id: '/ui-components/calendar',
    path: '/ui-components/calendar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ui-components/calendar.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUiComponentsButtonLazyRoute =
  AuthenticatedUiComponentsButtonLazyRouteImport.update({
    id: '/ui-components/button',
    path: '/ui-components/button',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ui-components/button.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUiComponentsBreadcrumbLazyRoute =
  AuthenticatedUiComponentsBreadcrumbLazyRouteImport.update({
    id: '/ui-components/breadcrumb',
    path: '/ui-components/breadcrumb',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ui-components/breadcrumb.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUiComponentsBadgeLazyRoute =
  AuthenticatedUiComponentsBadgeLazyRouteImport.update({
    id: '/ui-components/badge',
    path: '/ui-components/badge',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ui-components/badge.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUiComponentsAvatarLazyRoute =
  AuthenticatedUiComponentsAvatarLazyRouteImport.update({
    id: '/ui-components/avatar',
    path: '/ui-components/avatar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ui-components/avatar.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUiComponentsAlertDialogLazyRoute =
  AuthenticatedUiComponentsAlertDialogLazyRouteImport.update({
    id: '/ui-components/alert-dialog',
    path: '/ui-components/alert-dialog',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ui-components/alert-dialog.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUiComponentsAccordionLazyRoute =
  AuthenticatedUiComponentsAccordionLazyRouteImport.update({
    id: '/ui-components/accordion',
    path: '/ui-components/accordion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ui-components/accordion.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedSettingsProfileLazyRoute =
  AuthenticatedSettingsProfileLazyRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/profile.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedSettingsAppearanceLazyRoute =
  AuthenticatedSettingsAppearanceLazyRouteImport.update({
    id: '/settings/appearance',
    path: '/settings/appearance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/appearance.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedErrors503LazyRoute =
  AuthenticatedErrors503LazyRouteImport.update({
    id: '/errors/503',
    path: '/errors/503',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/errors/503.lazy').then((d) => d.Route),
  )
const AuthenticatedErrors500LazyRoute =
  AuthenticatedErrors500LazyRouteImport.update({
    id: '/errors/500',
    path: '/errors/500',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/errors/500.lazy').then((d) => d.Route),
  )
const AuthenticatedErrors404LazyRoute =
  AuthenticatedErrors404LazyRouteImport.update({
    id: '/errors/404',
    path: '/errors/404',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/errors/404.lazy').then((d) => d.Route),
  )
const AuthenticatedErrors403LazyRoute =
  AuthenticatedErrors403LazyRouteImport.update({
    id: '/errors/403',
    path: '/errors/403',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/errors/403.lazy').then((d) => d.Route),
  )
const AuthenticatedErrors401LazyRoute =
  AuthenticatedErrors401LazyRouteImport.update({
    id: '/errors/401',
    path: '/errors/401',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/errors/401.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexLazyRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/sign-up': typeof authSignUpRoute
  '/blank-page': typeof AuthenticatedBlankPageLazyRoute
  '/notifications': typeof AuthenticatedNotificationsLazyRoute
  '/users': typeof AuthenticatedUsersLazyRoute
  '/errors/401': typeof AuthenticatedErrors401LazyRoute
  '/errors/403': typeof AuthenticatedErrors403LazyRoute
  '/errors/404': typeof AuthenticatedErrors404LazyRoute
  '/errors/500': typeof AuthenticatedErrors500LazyRoute
  '/errors/503': typeof AuthenticatedErrors503LazyRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceLazyRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileLazyRoute
  '/ui-components/accordion': typeof AuthenticatedUiComponentsAccordionLazyRoute
  '/ui-components/alert-dialog': typeof AuthenticatedUiComponentsAlertDialogLazyRoute
  '/ui-components/avatar': typeof AuthenticatedUiComponentsAvatarLazyRoute
  '/ui-components/badge': typeof AuthenticatedUiComponentsBadgeLazyRoute
  '/ui-components/breadcrumb': typeof AuthenticatedUiComponentsBreadcrumbLazyRoute
  '/ui-components/button': typeof AuthenticatedUiComponentsButtonLazyRoute
  '/ui-components/calendar': typeof AuthenticatedUiComponentsCalendarLazyRoute
  '/ui-components/card': typeof AuthenticatedUiComponentsCardLazyRoute
  '/ui-components/checkbox': typeof AuthenticatedUiComponentsCheckboxLazyRoute
  '/ui-components/collapsible': typeof AuthenticatedUiComponentsCollapsibleLazyRoute
  '/ui-components/composite': typeof AuthenticatedUiComponentsCompositeLazyRoute
  '/ui-components/data-table': typeof AuthenticatedUiComponentsDataTableLazyRoute
  '/ui-components/date-picker': typeof AuthenticatedUiComponentsDatePickerLazyRoute
  '/ui-components/dropdown-menu': typeof AuthenticatedUiComponentsDropdownMenuLazyRoute
  '/ui-components/form': typeof AuthenticatedUiComponentsFormLazyRoute
  '/ui-components/form-validation': typeof AuthenticatedUiComponentsFormValidationLazyRoute
  '/ui-components/modal': typeof AuthenticatedUiComponentsModalLazyRoute
  '/ui-components/popover': typeof AuthenticatedUiComponentsPopoverLazyRoute
  '/ui-components/progress': typeof AuthenticatedUiComponentsProgressLazyRoute
  '/ui-components/radio-group': typeof AuthenticatedUiComponentsRadioGroupLazyRoute
  '/ui-components/school': typeof AuthenticatedUiComponentsSchoolLazyRoute
  '/ui-components/scroll-area': typeof AuthenticatedUiComponentsScrollAreaLazyRoute
  '/ui-components/select': typeof AuthenticatedUiComponentsSelectLazyRoute
  '/ui-components/separator': typeof AuthenticatedUiComponentsSeparatorLazyRoute
  '/ui-components/sheet': typeof AuthenticatedUiComponentsSheetLazyRoute
  '/ui-components/skeleton': typeof AuthenticatedUiComponentsSkeletonLazyRoute
  '/ui-components/switch': typeof AuthenticatedUiComponentsSwitchLazyRoute
  '/ui-components/tabs': typeof AuthenticatedUiComponentsTabsLazyRoute
  '/ui-components/toast': typeof AuthenticatedUiComponentsToastLazyRoute
  '/ui-components/tooltip': typeof AuthenticatedUiComponentsTooltipLazyRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/sign-up': typeof authSignUpRoute
  '/blank-page': typeof AuthenticatedBlankPageLazyRoute
  '/notifications': typeof AuthenticatedNotificationsLazyRoute
  '/users': typeof AuthenticatedUsersLazyRoute
  '/': typeof AuthenticatedIndexLazyRoute
  '/errors/401': typeof AuthenticatedErrors401LazyRoute
  '/errors/403': typeof AuthenticatedErrors403LazyRoute
  '/errors/404': typeof AuthenticatedErrors404LazyRoute
  '/errors/500': typeof AuthenticatedErrors500LazyRoute
  '/errors/503': typeof AuthenticatedErrors503LazyRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceLazyRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileLazyRoute
  '/ui-components/accordion': typeof AuthenticatedUiComponentsAccordionLazyRoute
  '/ui-components/alert-dialog': typeof AuthenticatedUiComponentsAlertDialogLazyRoute
  '/ui-components/avatar': typeof AuthenticatedUiComponentsAvatarLazyRoute
  '/ui-components/badge': typeof AuthenticatedUiComponentsBadgeLazyRoute
  '/ui-components/breadcrumb': typeof AuthenticatedUiComponentsBreadcrumbLazyRoute
  '/ui-components/button': typeof AuthenticatedUiComponentsButtonLazyRoute
  '/ui-components/calendar': typeof AuthenticatedUiComponentsCalendarLazyRoute
  '/ui-components/card': typeof AuthenticatedUiComponentsCardLazyRoute
  '/ui-components/checkbox': typeof AuthenticatedUiComponentsCheckboxLazyRoute
  '/ui-components/collapsible': typeof AuthenticatedUiComponentsCollapsibleLazyRoute
  '/ui-components/composite': typeof AuthenticatedUiComponentsCompositeLazyRoute
  '/ui-components/data-table': typeof AuthenticatedUiComponentsDataTableLazyRoute
  '/ui-components/date-picker': typeof AuthenticatedUiComponentsDatePickerLazyRoute
  '/ui-components/dropdown-menu': typeof AuthenticatedUiComponentsDropdownMenuLazyRoute
  '/ui-components/form': typeof AuthenticatedUiComponentsFormLazyRoute
  '/ui-components/form-validation': typeof AuthenticatedUiComponentsFormValidationLazyRoute
  '/ui-components/modal': typeof AuthenticatedUiComponentsModalLazyRoute
  '/ui-components/popover': typeof AuthenticatedUiComponentsPopoverLazyRoute
  '/ui-components/progress': typeof AuthenticatedUiComponentsProgressLazyRoute
  '/ui-components/radio-group': typeof AuthenticatedUiComponentsRadioGroupLazyRoute
  '/ui-components/school': typeof AuthenticatedUiComponentsSchoolLazyRoute
  '/ui-components/scroll-area': typeof AuthenticatedUiComponentsScrollAreaLazyRoute
  '/ui-components/select': typeof AuthenticatedUiComponentsSelectLazyRoute
  '/ui-components/separator': typeof AuthenticatedUiComponentsSeparatorLazyRoute
  '/ui-components/sheet': typeof AuthenticatedUiComponentsSheetLazyRoute
  '/ui-components/skeleton': typeof AuthenticatedUiComponentsSkeletonLazyRoute
  '/ui-components/switch': typeof AuthenticatedUiComponentsSwitchLazyRoute
  '/ui-components/tabs': typeof AuthenticatedUiComponentsTabsLazyRoute
  '/ui-components/toast': typeof AuthenticatedUiComponentsToastLazyRoute
  '/ui-components/tooltip': typeof AuthenticatedUiComponentsTooltipLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/_authenticated/blank-page': typeof AuthenticatedBlankPageLazyRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsLazyRoute
  '/_authenticated/users': typeof AuthenticatedUsersLazyRoute
  '/_authenticated/': typeof AuthenticatedIndexLazyRoute
  '/_authenticated/errors/401': typeof AuthenticatedErrors401LazyRoute
  '/_authenticated/errors/403': typeof AuthenticatedErrors403LazyRoute
  '/_authenticated/errors/404': typeof AuthenticatedErrors404LazyRoute
  '/_authenticated/errors/500': typeof AuthenticatedErrors500LazyRoute
  '/_authenticated/errors/503': typeof AuthenticatedErrors503LazyRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceLazyRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileLazyRoute
  '/_authenticated/ui-components/accordion': typeof AuthenticatedUiComponentsAccordionLazyRoute
  '/_authenticated/ui-components/alert-dialog': typeof AuthenticatedUiComponentsAlertDialogLazyRoute
  '/_authenticated/ui-components/avatar': typeof AuthenticatedUiComponentsAvatarLazyRoute
  '/_authenticated/ui-components/badge': typeof AuthenticatedUiComponentsBadgeLazyRoute
  '/_authenticated/ui-components/breadcrumb': typeof AuthenticatedUiComponentsBreadcrumbLazyRoute
  '/_authenticated/ui-components/button': typeof AuthenticatedUiComponentsButtonLazyRoute
  '/_authenticated/ui-components/calendar': typeof AuthenticatedUiComponentsCalendarLazyRoute
  '/_authenticated/ui-components/card': typeof AuthenticatedUiComponentsCardLazyRoute
  '/_authenticated/ui-components/checkbox': typeof AuthenticatedUiComponentsCheckboxLazyRoute
  '/_authenticated/ui-components/collapsible': typeof AuthenticatedUiComponentsCollapsibleLazyRoute
  '/_authenticated/ui-components/composite': typeof AuthenticatedUiComponentsCompositeLazyRoute
  '/_authenticated/ui-components/data-table': typeof AuthenticatedUiComponentsDataTableLazyRoute
  '/_authenticated/ui-components/date-picker': typeof AuthenticatedUiComponentsDatePickerLazyRoute
  '/_authenticated/ui-components/dropdown-menu': typeof AuthenticatedUiComponentsDropdownMenuLazyRoute
  '/_authenticated/ui-components/form': typeof AuthenticatedUiComponentsFormLazyRoute
  '/_authenticated/ui-components/form-validation': typeof AuthenticatedUiComponentsFormValidationLazyRoute
  '/_authenticated/ui-components/modal': typeof AuthenticatedUiComponentsModalLazyRoute
  '/_authenticated/ui-components/popover': typeof AuthenticatedUiComponentsPopoverLazyRoute
  '/_authenticated/ui-components/progress': typeof AuthenticatedUiComponentsProgressLazyRoute
  '/_authenticated/ui-components/radio-group': typeof AuthenticatedUiComponentsRadioGroupLazyRoute
  '/_authenticated/ui-components/school': typeof AuthenticatedUiComponentsSchoolLazyRoute
  '/_authenticated/ui-components/scroll-area': typeof AuthenticatedUiComponentsScrollAreaLazyRoute
  '/_authenticated/ui-components/select': typeof AuthenticatedUiComponentsSelectLazyRoute
  '/_authenticated/ui-components/separator': typeof AuthenticatedUiComponentsSeparatorLazyRoute
  '/_authenticated/ui-components/sheet': typeof AuthenticatedUiComponentsSheetLazyRoute
  '/_authenticated/ui-components/skeleton': typeof AuthenticatedUiComponentsSkeletonLazyRoute
  '/_authenticated/ui-components/switch': typeof AuthenticatedUiComponentsSwitchLazyRoute
  '/_authenticated/ui-components/tabs': typeof AuthenticatedUiComponentsTabsLazyRoute
  '/_authenticated/ui-components/toast': typeof AuthenticatedUiComponentsToastLazyRoute
  '/_authenticated/ui-components/tooltip': typeof AuthenticatedUiComponentsTooltipLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/sign-up'
    | '/blank-page'
    | '/notifications'
    | '/users'
    | '/errors/401'
    | '/errors/403'
    | '/errors/404'
    | '/errors/500'
    | '/errors/503'
    | '/settings/appearance'
    | '/settings/profile'
    | '/ui-components/accordion'
    | '/ui-components/alert-dialog'
    | '/ui-components/avatar'
    | '/ui-components/badge'
    | '/ui-components/breadcrumb'
    | '/ui-components/button'
    | '/ui-components/calendar'
    | '/ui-components/card'
    | '/ui-components/checkbox'
    | '/ui-components/collapsible'
    | '/ui-components/composite'
    | '/ui-components/data-table'
    | '/ui-components/date-picker'
    | '/ui-components/dropdown-menu'
    | '/ui-components/form'
    | '/ui-components/form-validation'
    | '/ui-components/modal'
    | '/ui-components/popover'
    | '/ui-components/progress'
    | '/ui-components/radio-group'
    | '/ui-components/school'
    | '/ui-components/scroll-area'
    | '/ui-components/select'
    | '/ui-components/separator'
    | '/ui-components/sheet'
    | '/ui-components/skeleton'
    | '/ui-components/switch'
    | '/ui-components/tabs'
    | '/ui-components/toast'
    | '/ui-components/tooltip'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/sign-up'
    | '/blank-page'
    | '/notifications'
    | '/users'
    | '/'
    | '/errors/401'
    | '/errors/403'
    | '/errors/404'
    | '/errors/500'
    | '/errors/503'
    | '/settings/appearance'
    | '/settings/profile'
    | '/ui-components/accordion'
    | '/ui-components/alert-dialog'
    | '/ui-components/avatar'
    | '/ui-components/badge'
    | '/ui-components/breadcrumb'
    | '/ui-components/button'
    | '/ui-components/calendar'
    | '/ui-components/card'
    | '/ui-components/checkbox'
    | '/ui-components/collapsible'
    | '/ui-components/composite'
    | '/ui-components/data-table'
    | '/ui-components/date-picker'
    | '/ui-components/dropdown-menu'
    | '/ui-components/form'
    | '/ui-components/form-validation'
    | '/ui-components/modal'
    | '/ui-components/popover'
    | '/ui-components/progress'
    | '/ui-components/radio-group'
    | '/ui-components/school'
    | '/ui-components/scroll-area'
    | '/ui-components/select'
    | '/ui-components/separator'
    | '/ui-components/sheet'
    | '/ui-components/skeleton'
    | '/ui-components/switch'
    | '/ui-components/tabs'
    | '/ui-components/toast'
    | '/ui-components/tooltip'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/sign-up'
    | '/_authenticated/blank-page'
    | '/_authenticated/notifications'
    | '/_authenticated/users'
    | '/_authenticated/'
    | '/_authenticated/errors/401'
    | '/_authenticated/errors/403'
    | '/_authenticated/errors/404'
    | '/_authenticated/errors/500'
    | '/_authenticated/errors/503'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/profile'
    | '/_authenticated/ui-components/accordion'
    | '/_authenticated/ui-components/alert-dialog'
    | '/_authenticated/ui-components/avatar'
    | '/_authenticated/ui-components/badge'
    | '/_authenticated/ui-components/breadcrumb'
    | '/_authenticated/ui-components/button'
    | '/_authenticated/ui-components/calendar'
    | '/_authenticated/ui-components/card'
    | '/_authenticated/ui-components/checkbox'
    | '/_authenticated/ui-components/collapsible'
    | '/_authenticated/ui-components/composite'
    | '/_authenticated/ui-components/data-table'
    | '/_authenticated/ui-components/date-picker'
    | '/_authenticated/ui-components/dropdown-menu'
    | '/_authenticated/ui-components/form'
    | '/_authenticated/ui-components/form-validation'
    | '/_authenticated/ui-components/modal'
    | '/_authenticated/ui-components/popover'
    | '/_authenticated/ui-components/progress'
    | '/_authenticated/ui-components/radio-group'
    | '/_authenticated/ui-components/school'
    | '/_authenticated/ui-components/scroll-area'
    | '/_authenticated/ui-components/select'
    | '/_authenticated/ui-components/separator'
    | '/_authenticated/ui-components/sheet'
    | '/_authenticated/ui-components/skeleton'
    | '/_authenticated/ui-components/switch'
    | '/_authenticated/ui-components/tabs'
    | '/_authenticated/ui-components/toast'
    | '/_authenticated/ui-components/tooltip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authSignUpRoute: typeof authSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blank-page': {
      id: '/_authenticated/blank-page'
      path: '/blank-page'
      fullPath: '/blank-page'
      preLoaderRoute: typeof AuthenticatedBlankPageLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ui-components/tooltip': {
      id: '/_authenticated/ui-components/tooltip'
      path: '/ui-components/tooltip'
      fullPath: '/ui-components/tooltip'
      preLoaderRoute: typeof AuthenticatedUiComponentsTooltipLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui-components/toast': {
      id: '/_authenticated/ui-components/toast'
      path: '/ui-components/toast'
      fullPath: '/ui-components/toast'
      preLoaderRoute: typeof AuthenticatedUiComponentsToastLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui-components/tabs': {
      id: '/_authenticated/ui-components/tabs'
      path: '/ui-components/tabs'
      fullPath: '/ui-components/tabs'
      preLoaderRoute: typeof AuthenticatedUiComponentsTabsLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui-components/switch': {
      id: '/_authenticated/ui-components/switch'
      path: '/ui-components/switch'
      fullPath: '/ui-components/switch'
      preLoaderRoute: typeof AuthenticatedUiComponentsSwitchLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui-components/skeleton': {
      id: '/_authenticated/ui-components/skeleton'
      path: '/ui-components/skeleton'
      fullPath: '/ui-components/skeleton'
      preLoaderRoute: typeof AuthenticatedUiComponentsSkeletonLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui-components/sheet': {
      id: '/_authenticated/ui-components/sheet'
      path: '/ui-components/sheet'
      fullPath: '/ui-components/sheet'
      preLoaderRoute: typeof AuthenticatedUiComponentsSheetLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui-components/separator': {
      id: '/_authenticated/ui-components/separator'
      path: '/ui-components/separator'
      fullPath: '/ui-components/separator'
      preLoaderRoute: typeof AuthenticatedUiComponentsSeparatorLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui-components/select': {
      id: '/_authenticated/ui-components/select'
      path: '/ui-components/select'
      fullPath: '/ui-components/select'
      preLoaderRoute: typeof AuthenticatedUiComponentsSelectLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui-components/scroll-area': {
      id: '/_authenticated/ui-components/scroll-area'
      path: '/ui-components/scroll-area'
      fullPath: '/ui-components/scroll-area'
      preLoaderRoute: typeof AuthenticatedUiComponentsScrollAreaLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui-components/school': {
      id: '/_authenticated/ui-components/school'
      path: '/ui-components/school'
      fullPath: '/ui-components/school'
      preLoaderRoute: typeof AuthenticatedUiComponentsSchoolLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui-components/radio-group': {
      id: '/_authenticated/ui-components/radio-group'
      path: '/ui-components/radio-group'
      fullPath: '/ui-components/radio-group'
      preLoaderRoute: typeof AuthenticatedUiComponentsRadioGroupLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui-components/progress': {
      id: '/_authenticated/ui-components/progress'
      path: '/ui-components/progress'
      fullPath: '/ui-components/progress'
      preLoaderRoute: typeof AuthenticatedUiComponentsProgressLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui-components/popover': {
      id: '/_authenticated/ui-components/popover'
      path: '/ui-components/popover'
      fullPath: '/ui-components/popover'
      preLoaderRoute: typeof AuthenticatedUiComponentsPopoverLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui-components/modal': {
      id: '/_authenticated/ui-components/modal'
      path: '/ui-components/modal'
      fullPath: '/ui-components/modal'
      preLoaderRoute: typeof AuthenticatedUiComponentsModalLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui-components/form-validation': {
      id: '/_authenticated/ui-components/form-validation'
      path: '/ui-components/form-validation'
      fullPath: '/ui-components/form-validation'
      preLoaderRoute: typeof AuthenticatedUiComponentsFormValidationLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui-components/form': {
      id: '/_authenticated/ui-components/form'
      path: '/ui-components/form'
      fullPath: '/ui-components/form'
      preLoaderRoute: typeof AuthenticatedUiComponentsFormLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui-components/dropdown-menu': {
      id: '/_authenticated/ui-components/dropdown-menu'
      path: '/ui-components/dropdown-menu'
      fullPath: '/ui-components/dropdown-menu'
      preLoaderRoute: typeof AuthenticatedUiComponentsDropdownMenuLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui-components/date-picker': {
      id: '/_authenticated/ui-components/date-picker'
      path: '/ui-components/date-picker'
      fullPath: '/ui-components/date-picker'
      preLoaderRoute: typeof AuthenticatedUiComponentsDatePickerLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui-components/data-table': {
      id: '/_authenticated/ui-components/data-table'
      path: '/ui-components/data-table'
      fullPath: '/ui-components/data-table'
      preLoaderRoute: typeof AuthenticatedUiComponentsDataTableLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui-components/composite': {
      id: '/_authenticated/ui-components/composite'
      path: '/ui-components/composite'
      fullPath: '/ui-components/composite'
      preLoaderRoute: typeof AuthenticatedUiComponentsCompositeLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui-components/collapsible': {
      id: '/_authenticated/ui-components/collapsible'
      path: '/ui-components/collapsible'
      fullPath: '/ui-components/collapsible'
      preLoaderRoute: typeof AuthenticatedUiComponentsCollapsibleLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui-components/checkbox': {
      id: '/_authenticated/ui-components/checkbox'
      path: '/ui-components/checkbox'
      fullPath: '/ui-components/checkbox'
      preLoaderRoute: typeof AuthenticatedUiComponentsCheckboxLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui-components/card': {
      id: '/_authenticated/ui-components/card'
      path: '/ui-components/card'
      fullPath: '/ui-components/card'
      preLoaderRoute: typeof AuthenticatedUiComponentsCardLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui-components/calendar': {
      id: '/_authenticated/ui-components/calendar'
      path: '/ui-components/calendar'
      fullPath: '/ui-components/calendar'
      preLoaderRoute: typeof AuthenticatedUiComponentsCalendarLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui-components/button': {
      id: '/_authenticated/ui-components/button'
      path: '/ui-components/button'
      fullPath: '/ui-components/button'
      preLoaderRoute: typeof AuthenticatedUiComponentsButtonLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui-components/breadcrumb': {
      id: '/_authenticated/ui-components/breadcrumb'
      path: '/ui-components/breadcrumb'
      fullPath: '/ui-components/breadcrumb'
      preLoaderRoute: typeof AuthenticatedUiComponentsBreadcrumbLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui-components/badge': {
      id: '/_authenticated/ui-components/badge'
      path: '/ui-components/badge'
      fullPath: '/ui-components/badge'
      preLoaderRoute: typeof AuthenticatedUiComponentsBadgeLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui-components/avatar': {
      id: '/_authenticated/ui-components/avatar'
      path: '/ui-components/avatar'
      fullPath: '/ui-components/avatar'
      preLoaderRoute: typeof AuthenticatedUiComponentsAvatarLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui-components/alert-dialog': {
      id: '/_authenticated/ui-components/alert-dialog'
      path: '/ui-components/alert-dialog'
      fullPath: '/ui-components/alert-dialog'
      preLoaderRoute: typeof AuthenticatedUiComponentsAlertDialogLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui-components/accordion': {
      id: '/_authenticated/ui-components/accordion'
      path: '/ui-components/accordion'
      fullPath: '/ui-components/accordion'
      preLoaderRoute: typeof AuthenticatedUiComponentsAccordionLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/503': {
      id: '/_authenticated/errors/503'
      path: '/errors/503'
      fullPath: '/errors/503'
      preLoaderRoute: typeof AuthenticatedErrors503LazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/500': {
      id: '/_authenticated/errors/500'
      path: '/errors/500'
      fullPath: '/errors/500'
      preLoaderRoute: typeof AuthenticatedErrors500LazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/404': {
      id: '/_authenticated/errors/404'
      path: '/errors/404'
      fullPath: '/errors/404'
      preLoaderRoute: typeof AuthenticatedErrors404LazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/403': {
      id: '/_authenticated/errors/403'
      path: '/errors/403'
      fullPath: '/errors/403'
      preLoaderRoute: typeof AuthenticatedErrors403LazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/401': {
      id: '/_authenticated/errors/401'
      path: '/errors/401'
      fullPath: '/errors/401'
      preLoaderRoute: typeof AuthenticatedErrors401LazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBlankPageLazyRoute: typeof AuthenticatedBlankPageLazyRoute
  AuthenticatedNotificationsLazyRoute: typeof AuthenticatedNotificationsLazyRoute
  AuthenticatedUsersLazyRoute: typeof AuthenticatedUsersLazyRoute
  AuthenticatedIndexLazyRoute: typeof AuthenticatedIndexLazyRoute
  AuthenticatedErrors401LazyRoute: typeof AuthenticatedErrors401LazyRoute
  AuthenticatedErrors403LazyRoute: typeof AuthenticatedErrors403LazyRoute
  AuthenticatedErrors404LazyRoute: typeof AuthenticatedErrors404LazyRoute
  AuthenticatedErrors500LazyRoute: typeof AuthenticatedErrors500LazyRoute
  AuthenticatedErrors503LazyRoute: typeof AuthenticatedErrors503LazyRoute
  AuthenticatedSettingsAppearanceLazyRoute: typeof AuthenticatedSettingsAppearanceLazyRoute
  AuthenticatedSettingsProfileLazyRoute: typeof AuthenticatedSettingsProfileLazyRoute
  AuthenticatedUiComponentsAccordionLazyRoute: typeof AuthenticatedUiComponentsAccordionLazyRoute
  AuthenticatedUiComponentsAlertDialogLazyRoute: typeof AuthenticatedUiComponentsAlertDialogLazyRoute
  AuthenticatedUiComponentsAvatarLazyRoute: typeof AuthenticatedUiComponentsAvatarLazyRoute
  AuthenticatedUiComponentsBadgeLazyRoute: typeof AuthenticatedUiComponentsBadgeLazyRoute
  AuthenticatedUiComponentsBreadcrumbLazyRoute: typeof AuthenticatedUiComponentsBreadcrumbLazyRoute
  AuthenticatedUiComponentsButtonLazyRoute: typeof AuthenticatedUiComponentsButtonLazyRoute
  AuthenticatedUiComponentsCalendarLazyRoute: typeof AuthenticatedUiComponentsCalendarLazyRoute
  AuthenticatedUiComponentsCardLazyRoute: typeof AuthenticatedUiComponentsCardLazyRoute
  AuthenticatedUiComponentsCheckboxLazyRoute: typeof AuthenticatedUiComponentsCheckboxLazyRoute
  AuthenticatedUiComponentsCollapsibleLazyRoute: typeof AuthenticatedUiComponentsCollapsibleLazyRoute
  AuthenticatedUiComponentsCompositeLazyRoute: typeof AuthenticatedUiComponentsCompositeLazyRoute
  AuthenticatedUiComponentsDataTableLazyRoute: typeof AuthenticatedUiComponentsDataTableLazyRoute
  AuthenticatedUiComponentsDatePickerLazyRoute: typeof AuthenticatedUiComponentsDatePickerLazyRoute
  AuthenticatedUiComponentsDropdownMenuLazyRoute: typeof AuthenticatedUiComponentsDropdownMenuLazyRoute
  AuthenticatedUiComponentsFormLazyRoute: typeof AuthenticatedUiComponentsFormLazyRoute
  AuthenticatedUiComponentsFormValidationLazyRoute: typeof AuthenticatedUiComponentsFormValidationLazyRoute
  AuthenticatedUiComponentsModalLazyRoute: typeof AuthenticatedUiComponentsModalLazyRoute
  AuthenticatedUiComponentsPopoverLazyRoute: typeof AuthenticatedUiComponentsPopoverLazyRoute
  AuthenticatedUiComponentsProgressLazyRoute: typeof AuthenticatedUiComponentsProgressLazyRoute
  AuthenticatedUiComponentsRadioGroupLazyRoute: typeof AuthenticatedUiComponentsRadioGroupLazyRoute
  AuthenticatedUiComponentsSchoolLazyRoute: typeof AuthenticatedUiComponentsSchoolLazyRoute
  AuthenticatedUiComponentsScrollAreaLazyRoute: typeof AuthenticatedUiComponentsScrollAreaLazyRoute
  AuthenticatedUiComponentsSelectLazyRoute: typeof AuthenticatedUiComponentsSelectLazyRoute
  AuthenticatedUiComponentsSeparatorLazyRoute: typeof AuthenticatedUiComponentsSeparatorLazyRoute
  AuthenticatedUiComponentsSheetLazyRoute: typeof AuthenticatedUiComponentsSheetLazyRoute
  AuthenticatedUiComponentsSkeletonLazyRoute: typeof AuthenticatedUiComponentsSkeletonLazyRoute
  AuthenticatedUiComponentsSwitchLazyRoute: typeof AuthenticatedUiComponentsSwitchLazyRoute
  AuthenticatedUiComponentsTabsLazyRoute: typeof AuthenticatedUiComponentsTabsLazyRoute
  AuthenticatedUiComponentsToastLazyRoute: typeof AuthenticatedUiComponentsToastLazyRoute
  AuthenticatedUiComponentsTooltipLazyRoute: typeof AuthenticatedUiComponentsTooltipLazyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBlankPageLazyRoute: AuthenticatedBlankPageLazyRoute,
  AuthenticatedNotificationsLazyRoute: AuthenticatedNotificationsLazyRoute,
  AuthenticatedUsersLazyRoute: AuthenticatedUsersLazyRoute,
  AuthenticatedIndexLazyRoute: AuthenticatedIndexLazyRoute,
  AuthenticatedErrors401LazyRoute: AuthenticatedErrors401LazyRoute,
  AuthenticatedErrors403LazyRoute: AuthenticatedErrors403LazyRoute,
  AuthenticatedErrors404LazyRoute: AuthenticatedErrors404LazyRoute,
  AuthenticatedErrors500LazyRoute: AuthenticatedErrors500LazyRoute,
  AuthenticatedErrors503LazyRoute: AuthenticatedErrors503LazyRoute,
  AuthenticatedSettingsAppearanceLazyRoute:
    AuthenticatedSettingsAppearanceLazyRoute,
  AuthenticatedSettingsProfileLazyRoute: AuthenticatedSettingsProfileLazyRoute,
  AuthenticatedUiComponentsAccordionLazyRoute:
    AuthenticatedUiComponentsAccordionLazyRoute,
  AuthenticatedUiComponentsAlertDialogLazyRoute:
    AuthenticatedUiComponentsAlertDialogLazyRoute,
  AuthenticatedUiComponentsAvatarLazyRoute:
    AuthenticatedUiComponentsAvatarLazyRoute,
  AuthenticatedUiComponentsBadgeLazyRoute:
    AuthenticatedUiComponentsBadgeLazyRoute,
  AuthenticatedUiComponentsBreadcrumbLazyRoute:
    AuthenticatedUiComponentsBreadcrumbLazyRoute,
  AuthenticatedUiComponentsButtonLazyRoute:
    AuthenticatedUiComponentsButtonLazyRoute,
  AuthenticatedUiComponentsCalendarLazyRoute:
    AuthenticatedUiComponentsCalendarLazyRoute,
  AuthenticatedUiComponentsCardLazyRoute:
    AuthenticatedUiComponentsCardLazyRoute,
  AuthenticatedUiComponentsCheckboxLazyRoute:
    AuthenticatedUiComponentsCheckboxLazyRoute,
  AuthenticatedUiComponentsCollapsibleLazyRoute:
    AuthenticatedUiComponentsCollapsibleLazyRoute,
  AuthenticatedUiComponentsCompositeLazyRoute:
    AuthenticatedUiComponentsCompositeLazyRoute,
  AuthenticatedUiComponentsDataTableLazyRoute:
    AuthenticatedUiComponentsDataTableLazyRoute,
  AuthenticatedUiComponentsDatePickerLazyRoute:
    AuthenticatedUiComponentsDatePickerLazyRoute,
  AuthenticatedUiComponentsDropdownMenuLazyRoute:
    AuthenticatedUiComponentsDropdownMenuLazyRoute,
  AuthenticatedUiComponentsFormLazyRoute:
    AuthenticatedUiComponentsFormLazyRoute,
  AuthenticatedUiComponentsFormValidationLazyRoute:
    AuthenticatedUiComponentsFormValidationLazyRoute,
  AuthenticatedUiComponentsModalLazyRoute:
    AuthenticatedUiComponentsModalLazyRoute,
  AuthenticatedUiComponentsPopoverLazyRoute:
    AuthenticatedUiComponentsPopoverLazyRoute,
  AuthenticatedUiComponentsProgressLazyRoute:
    AuthenticatedUiComponentsProgressLazyRoute,
  AuthenticatedUiComponentsRadioGroupLazyRoute:
    AuthenticatedUiComponentsRadioGroupLazyRoute,
  AuthenticatedUiComponentsSchoolLazyRoute:
    AuthenticatedUiComponentsSchoolLazyRoute,
  AuthenticatedUiComponentsScrollAreaLazyRoute:
    AuthenticatedUiComponentsScrollAreaLazyRoute,
  AuthenticatedUiComponentsSelectLazyRoute:
    AuthenticatedUiComponentsSelectLazyRoute,
  AuthenticatedUiComponentsSeparatorLazyRoute:
    AuthenticatedUiComponentsSeparatorLazyRoute,
  AuthenticatedUiComponentsSheetLazyRoute:
    AuthenticatedUiComponentsSheetLazyRoute,
  AuthenticatedUiComponentsSkeletonLazyRoute:
    AuthenticatedUiComponentsSkeletonLazyRoute,
  AuthenticatedUiComponentsSwitchLazyRoute:
    AuthenticatedUiComponentsSwitchLazyRoute,
  AuthenticatedUiComponentsTabsLazyRoute:
    AuthenticatedUiComponentsTabsLazyRoute,
  AuthenticatedUiComponentsToastLazyRoute:
    AuthenticatedUiComponentsToastLazyRoute,
  AuthenticatedUiComponentsTooltipLazyRoute:
    AuthenticatedUiComponentsTooltipLazyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authSignUpRoute: authSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
